module.exports = {
  allFunctions:
      [].concat(
          require('./array').functions,
          require('./boolean').functions,
          require('./cluster').functions,
          require('./display').functions,
          require('./events').functions,
          require('./groups').functions,
          require('./help').functions,
          require('./math').functions,
          require('./persons').functions,
          require('./sheets').functions,
          require('./staff').functions,
          require('./table').functions,
          require('./time').functions,
          require('./tuple').functions,
          require('./udf').functions,
          require('./util').functions,
          require('./wcif').functions,
      )
}
